---

- name: git remote add {{ inventory_hostname }} for {{ item.name }}
  shell: git remote add {{ inventory_hostname }} git@{{ ansible_hostname }}:{{ item.name }}
  args:
    chdir: "{{ item.local_dir }}"
  ignore_errors: yes
  become: no
  changed_when: False
  delegate_to: localhost
